### ISSUE TITLE
Couldn't install version 2.0.

### ISSUE THREAD

**Issue by naimkhalifa** [WillBrubaker/awesome-surveys#23]
I can't install version 2.0. Did you know about this issue? It says:

`Fatal error: Call to a member function register_post_type() on null in /home/vagrant/Code/labs/wp-awesome-survey/wp-content/plugins/awesome-surveys/awesome-surveys.php on line 110`

![awesome-survey-installation-error](https://cloud.githubusercontent.com/assets/7080564/6778973/e0801caa-d157-11e4-9ae3-baaf092289fb.png)

**Comment by WillBrubaker** [comment]
Yeah...somewhere I broke that. Sorry :( 
v2.0.2 fixed that.
