### ISSUE TITLE
Comment boxes go beyond edge of frame

### ISSUE THREAD

**Issue by fralippolippi** [WillBrubaker/awesome-surveys#34]
First, let me apologize for a few things: I am not WP savvy and I am not entirely sure I am articulating my question/issue very well. The problem may be entirely fixable by me, my knowledge/skill is just too limited for me to do so. 

So, I have a (test) survey but the text from either questions or possible answers can extend so far to the left that it disappears until finally, after about 60 characters (to include spaces) it will reappear to the right (wrap around). This does not happen for a normal "blog" post but only for the Survey's. 

Now, if I turn off the Survey option to include CSS this problem goes away however, a different problem presents itself - that is one where any kind of list (like checkboxes) becomes horrible. 

So, it seems like it may be something to do with the CSS being included but what/where I have no idea. All I really need is for the "frame" (my word) to be not as big so the words will wrap around. 

Any help would be appreciated.

**Comment by WillBrubaker** [comment]
Theme thing

**Comment by WillBrubaker** [comment]
Does this behavior happen with the default Twenty Fifteen theme active?
